# Notes on "Python for Data Science"
Course offered by University of Michigan on Coursera

## Basic String Manipulation

In [2]:
name = "Rohith KMS"
description = "nice guy"

name + ' is a ' + description

'Rohith KMS is a nice guy'

In [7]:
name[:6]

'Rohith'

In [9]:
name[-3:]

'KMS'

In [4]:
name.split(' ')

['Rohith', 'KMS']

In [10]:
first_name = name.split(' ')[0]
last_name = name.split(' ')[1]
print(first_name)
print(last_name)

Rohith
KMS


## Dictionaries

In [11]:
x = {'Rohith KMS': 'The awesomest guy on the planet', 'Pratyusha Madhnure': 'Dead Potato', 'Preetham':'Chikina', 
     'Babusha': 'Booska', 'Bhaskar': 'Boski', "Sharath": 'Psyduck'}

In [12]:
x.keys()

dict_keys(['Rohith KMS', 'Pratyusha Madhnure', 'Preetham', 'Babusha', 'Bhaskar', 'Sharath'])

In [13]:
x.values()

dict_values(['The awesomest guy on the planet', 'Dead Potato', 'Chikina', 'Booska', 'Boski', 'Psyduck'])

In [14]:
x.items()

dict_items([('Rohith KMS', 'The awesomest guy on the planet'), ('Pratyusha Madhnure', 'Dead Potato'), ('Preetham', 'Chikina'), ('Babusha', 'Booska'), ('Bhaskar', 'Boski'), ('Sharath', 'Psyduck')])

In [21]:
template = 'Did you know? {} is {}'

for name, nick in x.items():
    print(template.format(name, nick))

Did you know? Rohith KMS is The awesomest guy on the planet
Did you know? Pratyusha Madhnure is Dead Potato
Did you know? Preetham is Chikina
Did you know? Babusha is Booska
Did you know? Bhaskar is Boski
Did you know? Sharath is Psyduck


## Map() and lambda

In [24]:
num = [i for i in range(10)]

#Three ways to find list of squares.

[x**2 for x in num]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [27]:
def sqr(x):
    return x**2

list(map(sqr, num))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [28]:
list(map(lambda x: x**2, num))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

## List comprehension

In [4]:
letters = 'abcd'
numbers = '4568'
caps = 'DGHT'

#find all combinations like a4H, c5G etc...

[a+b+c for a in letters for b in numbers for c in caps][:10] #first 10 things

['a4D', 'a4G', 'a4H', 'a4T', 'a5D', 'a5G', 'a5H', 'a5T', 'a6D', 'a6G']

## Numpy

In [6]:
import numpy as np

In [8]:
a = np.array([x**2 for x in range(36)])
a = a.reshape(6,6)
a

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [26]:
a.reshape(36)[2::2] #every two elements starting from index 2

array([   4,   16,   36,   64,  100,  144,  196,  256,  324,  400,  484,
        576,  676,  784,  900, 1024, 1156])

In [32]:
a[2:4,2:4]

array([[196, 225],
       [400, 441]])